### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by mp911de** [pivotal-cf/spring-cloud-vault-connector#16]

**Comment by jim-mclean** [comment]
Is this going to get published?

**Comment by mp911de** [comment]
We're going to ship this version with the next Spring Vault release in January. With the 2.1 release, we're going to move this project into maintenance mode in favor of [Java CFEnv](https://github.com/pivotal-cf/java-cfenv).

**Comment by jim-mclean** [comment]
OK, thanks for the update.  Is CFEnv a functional replacement?  We're justing this lib in conjunction with Vault Service Broker backing service in PCF and Spring Cloud Vault Connector.

Right now we're broken because newer version of the Vault Service Broker for PCF changed the format of the JSON that describe the backends from a single element to an array...  Believe that's what described in #11

**Comment by mp911de** [comment]
CFEnv is intended as library that provides more flexibility. Connectors can be limited in their configuration abilities. You would use CFEnv mostly with configuration files. 

This connector provides slightly more functionality than CFEnv as the bound and pre-configured key-value backends are picked up as property sources.

**Comment by Ubunfu** [comment]
@mp911de So CFEnv won't automatically re-configure beans with the appropriate environment variables from a bound service?  If not then I would need to do that manually by using the CFEnv API to look them up and then plug the values into my own beans, right?
